# Generated by Django 3.1.7 on 2021-06-26 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Providers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('phone', models.CharField(max_length=10)),
                ('service', models.CharField(max_length=20)),
                ('about', models.TextField(max_length=80)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
    ]
