# Generated by Django 3.1.7 on 2021-06-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
