# Generated by Django 3.1.7 on 2021-06-26 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_login', '0002_providers_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='provider_images/'),
        ),
    ]
