# Generated by Django 3.1.7 on 2021-06-26 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('provider_login', '0003_providers_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='providers',
            name='profile_pic',
        ),
    ]
