# Generated by Django 3.1.7 on 2021-06-26 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_login', '0004_remove_providers_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='providers',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='provider_images/'),
        ),
    ]
