# Generated by Django 3.1.7 on 2021-06-26 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provider_login', '0007_auto_20210627_0315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='providers',
            name='profile_pic',
            field=models.ImageField(null=True, upload_to='provider_images/'),
        ),
    ]
