# Generated by Django 3.1.7 on 2021-06-23 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_login', '0002_auto_20210515_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(max_length=10),
        ),
    ]
