# Generated by Django 3.1.7 on 2021-06-27 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_login', '0004_auto_20210627_2220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='services',
        ),
        migrations.AddField(
            model_name='customer',
            name='pincode',
            field=models.CharField(default='None', max_length=6),
        ),
    ]
