# Generated by Django 3.1.7 on 2021-06-26 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0003_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='ser',
            field=models.CharField(max_length=20),
        ),
    ]
