# Generated by Django 3.1.7 on 2021-06-26 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_panel', '0004_auto_20210626_2344'),
    ]

    operations = [
        migrations.CreateModel(
            name='Locations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('pincode', models.CharField(max_length=6)),
            ],
        ),
        migrations.RenameField(
            model_name='services',
            old_name='ser',
            new_name='service',
        ),
    ]
