# Generated by Django 3.1.7 on 2021-06-28 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_remove_job_complete_within'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='complete_within',
            field=models.CharField(default='', max_length=20),
        ),
    ]
