# Generated by Django 3.1.7 on 2021-06-28 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0003_job_complete_within'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='address',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
