# Generated by Django 3.1.7 on 2021-06-28 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_job_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date_completed',
            field=models.DateTimeField(null=True),
        ),
    ]
